print('Witaj Świecie!')
print('jak masz na imię?')
my_name=input()
print('Miło Cię poznać, ' + my_name + '.')
print("liczba znaków w Twoim imieniu wynosi:")
print(len(my_name))
print("ile masz lat?")
my_age=input()
print('Za rok będziesz mieć ' + str(int(my_age)+1)+ ' lat.')
